# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prp < Formula
  desc "A convenient solution for backing up and restoring your installed packages."
  homepage "https://prp.io/"
  version "0.11"

  on_macos do
    url "https://github.com/Liopun/prp/releases/download/v0.11/prp_0.11_Darwin_x86_64.tar.gz"
    sha256 "a1bc8b5fb04510c47d883c2de1f526364b7376c961afa94bbf6628efeacdea6a"

    def install
      bin.install "prp"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Prp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Liopun/prp/releases/download/v0.11/prp_0.11_Linux_x86_64.tar.gz"
      sha256 "dae3fe234dd3cedb70ac644ff5a6d3f5699901e4a14bb5b18c99ae7ed6033ac6"

      def install
        bin.install "prp"
      end
    end
  end
end
