# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prp < Formula
  desc "A convenient solution for backing up and restoring your installed packages."
  homepage "https://prp.io/"
  version "0.12"

  on_macos do
    url "https://github.com/Liopun/prp/releases/download/v0.12/prp_0.12_Darwin_x86_64.tar.gz"
    sha256 "e7715062bef36d2e33e32097f022b4aef33a4fb3a1283762e05a9addc612e295"

    def install
      bin.install "prp"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Prp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Liopun/prp/releases/download/v0.12/prp_0.12_Linux_x86_64.tar.gz"
      sha256 "56c65426f96e2ba7c028adea6778781f2fd608aa8a92abe8f8e47e2adf9fda90"

      def install
        bin.install "prp"
      end
    end
  end
end
